name: Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code repository source code
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Run build
        run: yarn build

  docker-release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Release Docker Image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref }}
